### ISSUE TITLE
[Task] Implementation of filter function

### ISSUE THREAD

**Issue by Michael-gss** [gss-inc/gsslab-website-jp#1]
## To Do
Implementation of filter function

## Acceptance Criteria
* Implementation of filter function by "Skill"
* Implementation of filter function by "Rank"

## Definition of Done
* [ ] test evidence | [link]
* [ ] Pull request | [link]

## Working Hour
* Expected:
* Actual:

## Models and Diagrams (if needed)
<img width="1409" alt="Screen Shot 2022-10-17 at 1 41 15 PM" src="https://user-images.githubusercontent.com/49134688/196097782-f152590c-d075-490c-8585-9628d14f0f19.png">
https://gsslab-inc.com/resume/

## Translation
* Rank: ランク
* Skill: スキル

**Comment by Michael-gss** [comment]
test

**Comment by Kazuhisa-S** [comment]
* [x] test evidence | [https://www.loom.com/share/4a826f38f7a847d2800b249fd6d2826d]
* [x] Pull request | [https://github.com/gss-inc/gsslab-website-jp/issues/1]
