### ISSUE TITLE
[Task]Symbol (\) size adjustment at the top of the LP button

### ISSUE THREAD

**Issue by Kazuhisa-S** [gss-inc/gsslab-website-jp#13]
## To Do
Symbol (　\　) size adjustment at the top of the LP button

## Acceptance Criteria
* When the top symbol (　\　) of the "Interview Reservation" button on the LP is responsive, the size is changed, so the right side is positive as positive.

## Attention
* "The Japanese version and the English version are different HTML, so they will be corrected.
Since there are some LPs in the LP, all are corrected in the same way."

## Definition of Done
* [x] test evidence | [https://www.loom.com/share/a467b7155c7a46929f850b0148fea166]

## Working Hour
* Expected:
* Actual:

## Models and Diagrams
<img width="1138" alt="GSS_LAB_と_gss-inc_gsslab-website-jp" src="https://user-images.githubusercontent.com/114645823/196626718-952f9183-38a7-47a6-928c-a3b85b6231b2.png">

**Comment by Michael-gss** [comment]
@Kazuhisa-S 
Please check/delete this css 
<img width="693" alt="Screen Shot 2022-10-20 at 9 04 16 AM" src="https://user-images.githubusercontent.com/49134688/196832387-f765b567-6ef3-4f72-b388-65114a6ada5c.png">

**Comment by Kazuhisa-S** [comment]
Thank you

**Comment by Kazuhisa-S** [comment]
DONE
